openapi: 3.0.0
info:
  title: Пример API
  description: Это пример Swagger-спецификации в YAML файле.
  version: 1.0.0

paths:
  /hello:
    get:
      summary: Получить приветствие
      description: Возвращает приветствие с указанным именем.
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: Имя, для которого необходимо получить приветствие.
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Привет, Имя!"