version: '3'

services:
  postgres_db:
    image: postgres:14-alpine
    volumes:
      - animals_uploader_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: animals_db
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "docker_app" ]
      interval: 5s
      timeout: 5s
      retries: 3

  animals_upload:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres_db:5432/animals_db
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  animals_uploader_volume: