spring:
  application:
    name: TestTaskPUMB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/animals_db}
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    url: /swagger.yaml